version: "3"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./app:/go/src/github.com/camiloperezv/dojo_go/app
